<a href="https://colab.research.google.com/github/Requireding/QI_AGENT/blob/main/QI_AGENT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install datasets

Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.29.7)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.8.1)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (1.23.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.14.1)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2026.6.17)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2026.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.24.2)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (4.14.2)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

In [2]:
from datasets import load_dataset

In [3]:
dataset = load_dataset(
    "CShorten/ML-ArXiv-Papers",
    split="train"
)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/986 [00:00<?, ?B/s]

ML-Arxiv-Papers.csv: reconstructing file:   0%|          |  0.00B /  147MB

ML-Arxiv-Papers.csv: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/117592 [00:00<?, ? examples/s]

In [4]:
print(dataset)

Dataset({
    features: ['Unnamed: 0.1', 'Unnamed: 0', 'title', 'abstract'],
    num_rows: 117592
})

In [5]:
dataset[0]

{'Unnamed: 0.1': 0,
 'Unnamed: 0': 0.0,
 'title': 'Learning from compressed observations',
 'abstract': '  The problem of statistical learning is to construct a predictor of a random\nvariable $Y$ as a function of a related random variable $X$ on the basis of an\ni.i.d. training sample from the joint distribution of $(X,Y)$. Allowable\npredictors are drawn from some specified class, and the goal is to approach\nasymptotically the performance (expected loss) of the best predictor in the\nclass. We consider the setting in which one has perfect observation of the\n$X$-part of the sample, while the $Y$-part has to be communicated at some\nfinite bit rate. The encoding of the $Y$-values is allowed to depend on the\n$X$-values. Under suitable regularity conditions on the admissible predictors,\nthe underlying family of probability distributions and the loss function, we\ngive an information-theoretic characterization of achievable predictor\nperformance in terms of conditional distortion-rate functions. The ideas are\nillustrated on the example of nonparametric regression in Gaussian noise.\n'}

**Dataset into a Pandas DataFrame**

To load the data into a pandas DataFrame, we first need to ensure the `dataset` is available. We'll then convert it to a DataFrame and display its structure and head.

In [51]:
from datasets import load_dataset

dataset = load_dataset(
    "CShorten/ML-ArXiv-Papers",
    split="train"
)

In [22]:
import pandas as pd

df = pd.DataFrame(dataset)

print(df.info())
display(df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 117592 entries, 0 to 117591
Data columns (total 4 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Unnamed: 0.1  117592 non-null  int64
 1   Unnamed: 0    112592 non-null  float64
 2   title         117592 non-null  object
 3   abstract      117592 non-null  object
dtypes: float64(1), int64(1), object(2)
memory usage: 3.6+ MB
None

,Unnamed: 0.1,Unnamed: 0,title,abstract
0,0,0.0,Learning from compressed observations,The problem of statistical learning is to co...
1,1,1.0,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun..."
2,2,2.0,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...
3,3,3.0,A neural network approach to ordinal regression,Ordinal regression is an important type of l...
4,4,4.0,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...

In [52]:
import pandas as pd

df = pd.DataFrame(dataset)

print(df.info())
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 117592 entries, 0 to 117591
Data columns (total 4 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Unnamed: 0.1  117592 non-null  int64
 1   Unnamed: 0    112592 non-null  float64
 2   title         117592 non-null  object
 3   abstract      117592 non-null  object
dtypes: float64(1), int64(1), object(2)
memory usage: 3.6+ MB
None

,Unnamed: 0.1,Unnamed: 0,title,abstract
0,0,0.0,Learning from compressed observations,The problem of statistical learning is to co...
1,1,1.0,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun..."
2,2,2.0,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...
3,3,3.0,A neural network approach to ordinal regression,Ordinal regression is an important type of l...
4,4,4.0,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...

In [24]:
df.shape

(117592, 4)

In [8]:
df.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'title', 'abstract'], dtype='object')

In [53]:
df = df[['title', 'abstract']]

In [10]:
df.head()

,title,abstract
0,Learning from compressed observations,The problem of statistical learning is to co...
1,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun..."
2,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...
3,A neural network approach to ordinal regression,Ordinal regression is an important type of l...
4,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...

In [54]:
df = df.head(15000)

In [12]:
df.shape

(15000, 2)

In [13]:
df.isnull().sum()

title       0
abstract    0
dtype: int64

In [55]:
df["paper_text"] = df["title"] + " " + df["abstract"]

In [15]:
df[["paper_text"]].head()

                                          paper_text
0  Learning from compressed observations   The pr...
1  Sensor Networks with Random Links: Topology De...
2  The on-line shortest path problem under partia...
3  A neural network approach to ordinal regressio...
4  Parametric Learning and Monte Carlo Optimizati...

In [16]:
type(df[["paper_text"]])

pandas.core.frame.DataFrame

In [17]:
df["paper_text"].head()

0    Learning from compressed observations   The pr...
1    Sensor Networks with Random Links: Topology De...
2    The on-line shortest path problem under partia...
3    A neural network approach to ordinal regressio...
4    Parametric Learning and Monte Carlo Optimizati...
Name: paper_text, dtype: object

In [18]:
type(df["paper_text"])

pandas.core.series.Series

In [19]:
print(df["paper_text"].iloc[0])

Learning from compressed observations   The problem of statistical learning is to construct a predictor of a random
variable $Y$ as a function of a related random variable $X$ on the basis of an
i.i.d. training sample from the joint distribution of $(X,Y)$. Allowable
predictors are drawn from some specified class, and the goal is to approach
asymptotically the performance (expected loss) of the best predictor in the
class. We consider the setting in which one has perfect observation of the
$X$-part of the sample, while the $Y$-part has to be communicated at some
finite bit rate. The encoding of the $Y$-values is allowed to depend on the
$X$-values. Under suitable regularity conditions on the admissible predictors,
the underlying family of probability distributions and the loss function, we
give an information-theoretic characterization of achievable predictor
performance in terms of conditional distortion-rate functions. The ideas are
illustrated on the example of nonparametric regression in Gaussian noise.

In [56]:
df["paper_text"] = df["paper_text"].str.replace("\n", " ", regex=False)
df["paper_text"] = df["paper_text"].str.strip()

In [21]:
print(df["paper_text"].iloc[0])

Learning from compressed observations   The problem of statistical learning is to construct a predictor of a random variable $Y$ as a function of a related random variable $X$ on the basis of an i.i.d. training sample from the joint distribution of $(X,Y)$. Allowable predictors are drawn from some specified class, and the goal is to approach asymptotically the performance (expected loss) of the best predictor in the class. We consider the setting in which one has perfect observation of the $X$-part of the sample, while the $Y$-part has to be communicated at some finite bit rate. The encoding of the $Y$-values is allowed to depend on the $X$-values. Under suitable regularity conditions on the admissible predictors, the underlying family of probability distributions and the loss function, we give an information-theoretic characterization of achievable predictor performance in terms of conditional distortion-rate functions. The ideas are illustrated on the example of nonparametric regression in Gaussian noise.

**Sentence Transformers**

In [22]:
from sentence_transformers import SentenceTransformer

In [57]:
model = SentenceTransformer('all-MiniLM-L6-v2')

In [24]:
print(type(model))

<class 'sentence_transformers.sentence_transformer.model.SentenceTransformer'>

In [25]:
sample_text = df["paper_text"].iloc[0]

embedding = model.encode(sample_text)

print(type(embedding))
print(embedding.shape)

<class 'numpy.ndarray'>
(384,)

In [26]:
embedding[:10]

array([-0.1315641 , -0.00678266, -0.00367612,  0.03265158,  0.11219642,
        0.01227267,  0.09816719, -0.0900523 ,  0.04231161, -0.01977348],
      dtype=float32)

In [27]:
sample_embeddings = model.encode(
    df["paper_text"].head(5).tolist()
)

print(type(sample_embeddings))
print(sample_embeddings.shape)

<class 'numpy.ndarray'>
(5, 384)

In [28]:
from sklearn.metrics.pairwise import cosine_similarity

In [29]:
similarity = cosine_similarity(
    sample_embeddings[0].reshape(1, -1),
    sample_embeddings[1].reshape(1, -1)
)

print(similarity)

[[0.36625272]]

In [30]:
similarity = cosine_similarity(
    sample_embeddings[0].reshape(1,-1),
    sample_embeddings[0].reshape(1,-1)
)

print(similarity)

[[1.0000001]]

In [31]:
for i in range(1,5):

    sim = cosine_similarity(
        sample_embeddings[0].reshape(1,-1),
        sample_embeddings[i].reshape(1,-1)
    )

    print(f"Paper 1 vs Paper {i+1}: {sim[0][0]:.4f}")

Paper 1 vs Paper 2: 0.3663
Paper 1 vs Paper 3: 0.3352
Paper 1 vs Paper 4: 0.1551
Paper 1 vs Paper 5: 0.3742

**Generate Full Embeddings**

In [58]:
import os
import numpy as np

if os.path.exists("paper_embeddings.npy"):

    print("Loading saved embeddings...")

    embeddings = np.load("paper_embeddings.npy")

else:

    print("Generating embeddings...")

    embeddings = model.encode(
        df["paper_text"].tolist(),
        batch_size=32,
        show_progress_bar=True
    )

    np.save("paper_embeddings.npy", embeddings)

    print("Embeddings saved successfully!")

Loading saved embeddings...

In [33]:
print(type(embeddings))
print(embeddings.shape)

<class 'numpy.ndarray'>
(15000, 384)

In [34]:
embeddings.nbytes / (1024*1024)

21.97265625

In [35]:
embeddings.dtype

dtype('float32')

In [36]:
!pip install faiss-cpu

Collecting faiss-cpu
  Downloading faiss_cpu-1.14.3-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (7.8 kB)
Requirement already satisfied: numpy>=1.25 in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (26.2)
Downloading faiss_cpu-1.14.3-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (18.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.5/18.5 MB 45.9 MB/s eta 0:00:00
Installing collected packages: faiss-cpu
Successfully installed faiss-cpu-1.14.3

In [59]:
import os
import faiss

if os.path.exists("paper_faiss.index"):

    print("Loading existing FAISS index...")

    index = faiss.read_index("paper_faiss.index")

else:

    print("Creating new FAISS index...")

    faiss.normalize_L2(embeddings)

    index = faiss.IndexFlatIP(384)

    index.add(embeddings)

    faiss.write_index(index, "paper_faiss.index")

    print("FAISS index saved successfully!")

Loading existing FAISS index...

In [38]:
import numpy as np

np.linalg.norm(embeddings[0])

np.float32(1.0)

In [39]:
print(index.ntotal)

15000

In [40]:
query = "deep learning for medical image analysis"
query_embedding = model.encode([query])
query_embedding.shape

(1, 384)

In [41]:
faiss.normalize_L2(query_embedding)


np.linalg.norm(query_embedding[0])

np.float32(1.0)

In [42]:
D, I = index.search(query_embedding, 5)

print(D)
print(I)

[[0.6807244  0.67092204 0.65219975 0.62811744 0.61311525]]
[[10466 13730 11873 12691 11282]]

In [43]:
print(df.iloc[10466]["title"])

A Perspective on Deep Imaging

In [44]:
print(df.iloc[10466]["abstract"])

  The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance in clinical and
preclinical applications. To realize the full impact of machine learning on
medical imaging, major challenges must be addressed.

In [45]:
def search_papers(query, k=5):

    query_embedding = model.encode([query])

    faiss.normalize_L2(query_embedding)

    D, I = index.search(query_embedding, k)

    return D, I

In [46]:
D, I = search_papers(
    "deep learning for medical image analysis"
)

print(D)
print(I)

[[0.6807244  0.67092204 0.65219975 0.62811744 0.61311525]]
[[10466 13730 11873 12691 11282]]

In [47]:
def search_papers(query, k=5):

    query_embedding = model.encode([query])

    faiss.normalize_L2(query_embedding)

    D, I = index.search(query_embedding, k)

    for score, idx in zip(D[0], I[0]):

        print("=" * 100)

        print("Similarity:", round(float(score), 4))

        print("Title:", df.iloc[idx]["title"])

        print()

        print("Abstract:")

        print(df.iloc[idx]["abstract"][:500])

        print()

In [48]:
search_papers(
    "deep learning for medical image analysis"
)

====================================================================================================
Similarity: 0.6807
Title: A Perspective on Deep Imaging

Abstract:
  The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance

====================================================================================================
Similarity: 0.6709
Title: Convolutional Neural Networks for Medical Image Analysis: Full Training
  or Fine Tuning?

Abstract:
  Training a deep convolutional neural network (CNN) from scratch is difficult
because it requires a large amount of labeled training data and a great deal of
expertise to ensure proper convergence. A promising alternative is to fine-tune
a CNN that has been pre-trained using, for instance, a large set of labeled
natural images. However, the substantial differences between natural and
medical images may advise against such knowledge transfer. In this paper, we
seek to answer the following centra

====================================================================================================
Similarity: 0.6522
Title: Classification of MRI data using Deep Learning and Gaussian
  Process-based Model Selection

Abstract:
  The classification of MRI images according to the anatomical field of view is
a necessary task to solve when faced with the increasing quantity of medical
images. In parallel, advances in deep learning makes it a suitable tool for
computer vision problems. Using a common architecture (such as AlexNet)
provides quite good results, but not sufficient for clinical use. Improving the
model is not an easy task, due to the large number of hyper-parameters
governing both the architecture and the trai

====================================================================================================
Similarity: 0.6281
Title: High-Resolution Breast Cancer Screening with Multi-View Deep
  Convolutional Neural Networks

Abstract:
  Advances in deep learning for natural images have prompted a surge of
interest in applying similar techniques to medical images. The majority of the
initial attempts focused on replacing the input of a deep convolutional neural
network with a medical image, which does not take into consideration the
fundamental differences between these two types of images. Specifically, fine
details are necessary for detection in medical images, unlike in natural images
where coarse structures matter most. Th

====================================================================================================
Similarity: 0.6131
Title: Deep Learning for the Classification of Lung Nodules

Abstract:
  Deep learning, as a promising new area of machine learning, has attracted a
rapidly increasing attention in the field of medical imaging. Compared to the
conventional machine learning methods, deep learning requires no hand-tuned
feature extractor, and has shown a superior performance in many visual object
recognition applications. In this study, we develop a deep convolutional neural
network (CNN) and apply it to thoracic CT images for the classification of lung
nodules. We present the CNN ar

In [49]:
!pip install \
transformers==4.46.3 \
huggingface_hub==0.26.2 \
tokenizers==0.20.3 \
sentence-transformers==3.3.1

Collecting transformers==4.46.3
  Downloading transformers-4.46.3-py3-none-any.whl.metadata (44 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.1/44.1 kB 1.9 MB/s eta 0:00:00
Collecting huggingface_hub==0.26.2
  Downloading huggingface_hub-0.26.2-py3-none-any.whl.metadata (13 kB)
Collecting tokenizers==0.20.3
  Downloading tokenizers-0.20.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Collecting sentence-transformers==3.3.1
  Downloading sentence_transformers-3.3.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (3.29.7)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (2.32.4)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (0.8.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (4.67.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub==0.26.2) (2025.3.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub==0.26.2) (4.16.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers==3.3.1) (2.11.0+cpu)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from sentence-transformers==3.3.1) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers==3.3.1) (1.16.3)
Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (from sentence-transformers==3.3.1) (11.3.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers==3.3.1) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers==3.3.1) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers==3.3.1) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers==3.3.1) (3.1.6)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.46.3) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.46.3) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.46.3) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.46.3) (2026.6.17)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers==3.3.1) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers==3.3.1) (3.6.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers==3.3.1) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers==3.3.1) (3.0.3)
Downloading transformers-4.46.3-py3-none-any.whl (10.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 19.2 MB/s eta 0:00:00
Downloading huggingface_hub-0.26.2-py3-none-any.whl (447 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 447.5/447.5 kB 10.2 MB/s eta 0:00:00
Downloading tokenizers-0.20.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 24.5 MB/s eta 0:00:00
Downloading sentence_transformers-3.3.1-py3-none-any.whl (268 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 9.2 MB/s eta 0:00:00
Installing collected packages: huggingface_hub, tokenizers, transformers, sentence-transformers
  Attempting uninstall: huggingface_hub
    Found existing installation: huggingface_hub 1.23.0
    Uninstalling huggingface_hub-1.23.0:
      Successfully uninstalled huggingface_hub-1.23.0
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.22.2
    Uninstalling tokenizers-0.22.2:
      Successfully uninstalled tokenizers-0.22.2
  Attempting uninstall: transformers
    Found existing installation: transformers 5.13.1
    Uninstalling transformers-5.13.1:
      Successfully uninstalled transformers-5.13.1
  Attempting uninstall: sentence-transformers
    Found existing installation: sentence-transformers 5.6.0
    Uninstalling sentence-transformers-5.6.0:
      Successfully uninstalled sentence-transformers-5.6.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
diffusers 0.39.0 requires huggingface-hub<2.0,>=0.34.0, but you have huggingface-hub 0.26.2 which is incompatible.
gradio 6.20.0 requires huggingface-hub<2.0,>=1.2.0, but you have huggingface-hub 0.26.2 which is incompatible.
Successfully installed huggingface_hub-0.26.2 sentence-transformers-3.3.1 tokenizers-0.20.3 transformers-4.46.3

In [1]:
import transformers
import huggingface_hub

print("Transformers:", transformers.__version__)
print("Transformers Path:", transformers.__file__)

print("Hub:", huggingface_hub.__version__)
print("Hub Path:", huggingface_hub.__file__)

import transformers.utils as u

print(hasattr(u, "HUGGINGFACE_CO_RESOLVE_ENDPOINT"))

The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.

0it [00:00, ?it/s]

Transformers: 4.46.3
Transformers Path: /usr/local/lib/python3.12/dist-packages/transformers/__init__.py
Hub: 0.26.2
Hub Path: /usr/local/lib/python3.12/dist-packages/huggingface_hub/__init__.py
True

In [2]:
import transformers.utils as u

print(hasattr(u, "HUGGINGFACE_CO_RESOLVE_ENDPOINT"))

True

In [3]:
from transformers import pipeline

WARNING:torchao.kernel.intmm:Warning: Detected no triton, on systems without Triton certain kernels will not work

In [4]:
type(pipeline)

function

In [60]:
summarizer = pipeline(
    "summarization",
    model="facebook/bart-large-cnn"
)

In [6]:
type(summarizer)

transformers.pipelines.text2text_generation.SummarizationPipeline

In [25]:
summary = summarizer(
    df.iloc[10466]["abstract"],
    max_length=120,
    min_length=40,
    do_sample=False
)

In [26]:
print(summary)

[{'summary_text': 'The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image reconstructions. This direction might lead to intelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in clinical applications.'}]

In [27]:
type(summary)

list

In [28]:
summary[0]

{'summary_text': 'The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image reconstructions. This direction might lead to intelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in clinical applications.'}

In [29]:
type(summary[0])

dict

In [30]:
summary[0]["summary_text"]

'The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image reconstructions. This direction might lead to intelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in clinical applications.'

In [31]:
print(summary[0]["summary_text"])

The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image reconstructions. This direction might lead to intelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in clinical applications.

In [38]:
from sentence_transformers import SentenceTransformer
import faiss
import os
from transformers import pipeline

model = SentenceTransformer('all-MiniLM-L6-v2')

# Initialize summarizer pipeline
summarizer = pipeline(
    "summarization",
    model="facebook/bart-large-cnn"
)

# Load the FAISS index
if os.path.exists("paper_faiss.index"):
    print("Loading existing FAISS index...")
    index = faiss.read_index("paper_faiss.index")
else:
    raise FileNotFoundError("FAISS index file 'paper_faiss.index' not found. Please ensure it has been created and saved.")

query = "deep learning for medical image analysis" # Example query
query_embedding = model.encode([query])
faiss.normalize_L2(query_embedding)
D, I = index.search(query_embedding, 5) # Perform the search to define D and I

for score, idx in zip(D[0], I[0]):

    print("=" * 100)

    print("Similarity:", round(float(score), 4))

    print("Title:", df.iloc[idx]["title"])

    print()

    summary = summarizer(
        df.iloc[idx]["abstract"],
        max_length=120,
        min_length=40,
        do_sample=False
    )

    print("Summary:")

    print(summary[0]["summary_text"])

    print()

Loading existing FAISS index...
====================================================================================================
Similarity: 0.6807
Title: A Perspective on Deep Imaging

Summary:
The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image reconstructions. This direction might lead to intelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in clinical applications.

====================================================================================================
Similarity: 0.6709
Title: Convolutional Neural Networks for Medical Image Analysis: Full Training
  or Fine Tuning?

Summary:
Training a deep convolutional neural network from scratch is difficult because it requires a large amount of labeled training data. A promising alternative is to fine-tune a CNN that has been pre-trained using, for instance, a large set of labeled natural images.

====================================================================================================
Similarity: 0.6522
Title: Classification of MRI data using Deep Learning and Gaussian
  Process-based Model Selection

Summary:
The classification of MRI images according to the anatomical field of view is a necessary task to solve when faced with the increasing quantity of medical images. Using a common architecture (such as AlexNet) provides quite good results, but not sufficient for clinical use.

====================================================================================================
Similarity: 0.6281
Title: High-Resolution Breast Cancer Screening with Multi-View Deep
  Convolutional Neural Networks

Summary:
The study used a set of high-resolution images to test the accuracy of the neural network. It found that the network performed better than expected when it was given a large set of images to work with.

====================================================================================================
Similarity: 0.6131
Title: Deep Learning for the Classification of Lung Nodules

Summary:
Deep learning, as a promising new area of machine learning, has attracted a rapidly increasing attention in the field of medical imaging. In this study, we develop a deep convolutional neuralnetwork (CNN) and apply it to thoracic CT images for the classification of lung nodules.

In [39]:
def summarize_text(text):

    summary = summarizer(
        text,
        max_length=120,
        min_length=40,
        do_sample=False
    )

    return summary[0]["summary_text"]

In [40]:
def search_and_summarize(query, k=5):

    query_embedding = model.encode([query])

    faiss.normalize_L2(query_embedding)

    D, I = index.search(query_embedding, k)

    for score, idx in zip(D[0], I[0]):

        print("=" * 100)

        print("Similarity:", round(float(score), 4))

        print("Title:", df.iloc[idx]["title"])

        print()

        summary = summarizer(
            df.iloc[idx]["abstract"],
            max_length=120,
            min_length=40,
            do_sample=False
        )

        print("Summary:")

        print(summary[0]["summary_text"])

        print()

In [41]:
search_and_summarize(
    "Deep Learning in Medical Imaging",
    k=5
)

====================================================================================================
Similarity: 0.7355
Title: A Perspective on Deep Imaging

Summary:
The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image reconstructions. This direction might lead to intelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in clinical applications.

====================================================================================================
Similarity: 0.6882
Title: Classification of MRI data using Deep Learning and Gaussian
  Process-based Model Selection

Summary:
The classification of MRI images according to the anatomical field of view is a necessary task to solve when faced with the increasing quantity of medical images. Using a common architecture (such as AlexNet) provides quite good results, but not sufficient for clinical use.

====================================================================================================
Similarity: 0.6532
Title: Convolutional Neural Networks for Medical Image Analysis: Full Training
  or Fine Tuning?

Summary:
Training a deep convolutional neural network from scratch is difficult because it requires a large amount of labeled training data. A promising alternative is to fine-tune a CNN that has been pre-trained using, for instance, a large set of labeled natural images.

====================================================================================================
Similarity: 0.6222
Title: High-Resolution Breast Cancer Screening with Multi-View Deep
  Convolutional Neural Networks

Summary:
The study used a set of high-resolution images to test the accuracy of the neural network. It found that the network performed better than expected when it was given a large set of images to work with.

====================================================================================================
Similarity: 0.6151
Title: Deep Learning Microscopy

Summary:
We demonstrate that a deep neural network can significantly improve opticalmicroscopy. After its training, the only input to this network is an imageacquired using a regular optical microscope, without any changes to its design. These results are transformative for various fields that use microscopy tools.

In [42]:
!pip install keybert==0.8.5

Collecting keybert==0.8.5
  Downloading keybert-0.8.5-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from keybert==0.8.5) (2.0.2)
Requirement already satisfied: rich>=10.4.0 in /usr/local/lib/python3.12/dist-packages (from keybert==0.8.5) (13.9.4)
Requirement already satisfied: scikit-learn>=0.22.2 in /usr/local/lib/python3.12/dist-packages (from keybert==0.8.5) (1.6.1)
Requirement already satisfied: sentence-transformers>=0.3.8 in /usr/local/lib/python3.12/dist-packages (from keybert==0.8.5) (3.3.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.4.0->keybert==0.8.5) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.4.0->keybert==0.8.5) (2.20.0)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.2->keybert==0.8.5) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.2->keybert==0.8.5) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.2->keybert==0.8.5) (3.6.0)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.3.8->keybert==0.8.5) (4.46.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.3.8->keybert==0.8.5) (4.67.3)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.3.8->keybert==0.8.5) (2.11.0+cpu)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.3.8->keybert==0.8.5) (0.26.2)
Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.3.8->keybert==0.8.5) (11.3.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.3.8->keybert==0.8.5) (3.29.7)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.3.8->keybert==0.8.5) (2025.3.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.3.8->keybert==0.8.5) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.3.8->keybert==0.8.5) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.3.8->keybert==0.8.5) (2.32.4)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.3.8->keybert==0.8.5) (4.16.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=10.4.0->keybert==0.8.5) (0.1.2)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert==0.8.5) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert==0.8.5) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert==0.8.5) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert==0.8.5) (3.1.6)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert==0.8.5) (2025.11.3)
Requirement already satisfied: tokenizers<0.21,>=0.20 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert==0.8.5) (0.20.3)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert==0.8.5) (0.8.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers>=0.3.8->keybert==0.8.5) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers>=0.3.8->keybert==0.8.5) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.3.8->keybert==0.8.5) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.3.8->keybert==0.8.5) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.3.8->keybert==0.8.5) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.3.8->keybert==0.8.5) (2026.6.17)
Downloading keybert-0.8.5-py3-none-any.whl (37 kB)
Installing collected packages: keybert
Successfully installed keybert-0.8.5

In [43]:
from keybert import KeyBERT

In [61]:
kw_model = KeyBERT(model)

In [45]:
type(kw_model)

keybert._model.KeyBERT

In [46]:
text = df.iloc[10466]["abstract"]

keywords = kw_model.extract_keywords(text)

In [47]:
print(type(keywords))

<class 'list'>

In [48]:
print(type(keywords[0]))

<class 'tuple'>

In [49]:
print(keywords[0])

('imaging', 0.4528)

In [50]:
keywords = kw_model.extract_keywords(
    text,
    keyphrase_ngram_range=(1,3),
    stop_words="english",
    top_n=5
)

print(keywords)

[('tomographic imaging deep', 0.6704), ('imaging deep learning', 0.6543), ('learning medical imaging', 0.6041), ('imaging deep', 0.5919), ('medical imaging', 0.5281)]

In [51]:
def search_and_summarize(query, k=5):

    query_embedding = model.encode([query])

    faiss.normalize_L2(query_embedding)

    D, I = index.search(query_embedding, k)

    for score, idx in zip(D[0], I[0]):

        print("=" * 100)

        print("Similarity:", round(float(score), 4))

        print("Title:", df.iloc[idx]["title"])

        print()

        summary = summarizer(
            df.iloc[idx]["abstract"],
            max_length=120,
            min_length=40,
            do_sample=False
        )

        print("Summary:")

        print(summary[0]["summary_text"])

        print()

        keywords = kw_model.extract_keywords(
            df.iloc[idx]["abstract"],
            keyphrase_ngram_range=(1,3),
            stop_words="english",
            top_n=5
        )

        print("Keywords:")

        for keyword, score in keywords:
            print("-", keyword)

        print()

In [52]:
search_and_summarize(
    "Deep Learning in Medical Imaging",
    k=5
)

====================================================================================================
Similarity: 0.7355
Title: A Perspective on Deep Imaging

Summary:
The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image reconstructions. This direction might lead to intelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in clinical applications.

Keywords:
- tomographic imaging deep
- imaging deep learning
- learning medical imaging
- imaging deep
- medical imaging

====================================================================================================
Similarity: 0.6882
Title: Classification of MRI data using Deep Learning and Gaussian
  Process-based Model Selection

Summary:
The classification of MRI images according to the anatomical field of view is a necessary task to solve when faced with the increasing quantity of medical images. Using a common architecture (such as AlexNet) provides quite good results, but not sufficient for clinical use.

Keywords:
- classification mri images
- classification mri
- mri dataset substantial
- mri dataset
- advances deep learning

====================================================================================================
Similarity: 0.6532
Title: Convolutional Neural Networks for Medical Image Analysis: Full Training
  or Fine Tuning?

Summary:
Training a deep convolutional neural network from scratch is difficult because it requires a large amount of labeled training data. A promising alternative is to fine-tune a CNN that has been pre-trained using, for instance, a large set of labeled natural images.

Keywords:
- trained cnns fine
- cnn adequate fine
- training deep cnn
- cnns sufficient fine
- cnn pre trained

====================================================================================================
Similarity: 0.6222
Title: High-Resolution Breast Cancer Screening with Multi-View Deep
  Convolutional Neural Networks

Summary:
The study used a set of high-resolution images to test the accuracy of the neural network. It found that the network performed better than expected when it was given a large set of images to work with.

Keywords:
- large scale mammography
- view deep convolutional
- learning natural images
- multi view deep
- deep learning natural

====================================================================================================
Similarity: 0.6151
Title: Deep Learning Microscopy

Summary:
We demonstrate that a deep neural network can significantly improve opticalmicroscopy. After its training, the only input to this network is an imageacquired using a regular optical microscope, without any changes to its design. These results are transformative for various fields that use microscopy tools.

Keywords:
- improve optical microscopy
- fields use microscopy
- optical microscopy
- optical microscopy enhancing
- sciences optical microscopy

**Hybrid NER Architecture**

In [53]:
ner = pipeline(
    "ner",
    aggregation_strategy="simple"
)

No model was supplied, defaulted to dbmdz/bert-large-cased-finetuned-conll03-english and revision 4c53496 (https://huggingface.co/dbmdz/bert-large-cased-finetuned-conll03-english).
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json:   0%|          | 0.00/998 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.33G [00:00<?, ?B/s]

Some weights of the model checkpoint at dbmdz/bert-large-cased-finetuned-conll03-english were not used when initializing BertForTokenClassification: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
- This IS expected if you are initializing BertForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

tokenizer_config.json:   0%|          | 0.00/60.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

In [54]:
text = """
ResNet50 was trained on ImageNet using PyTorch
at Stanford University.
"""
entities = ner(text)

print(entities)

[{'entity_group': 'ORG', 'score': np.float32(0.89313775), 'word': 'ResNet50', 'start': 1, 'end': 9}, {'entity_group': 'ORG', 'score': np.float32(0.82662463), 'word': 'ImageNet', 'start': 25, 'end': 33}, {'entity_group': 'ORG', 'score': np.float32(0.94511735), 'word': 'PyTorch', 'start': 40, 'end': 47}, {'entity_group': 'ORG', 'score': np.float32(0.93374425), 'word': 'Stanford University', 'start': 51, 'end': 70}]

In [55]:
!pip install langchain langchain-community langchain-core

Requirement already satisfied: langchain in /usr/local/lib/python3.12/dist-packages (1.3.13)
Collecting langchain-community
  Downloading langchain_community-0.4.2-py3-none-any.whl.metadata (3.4 kB)
Requirement already satisfied: langchain-core in /usr/local/lib/python3.12/dist-packages (1.4.9)
Requirement already satisfied: langgraph<1.3.0,>=1.2.5 in /usr/local/lib/python3.12/dist-packages (from langchain) (1.2.9)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain) (2.13.4)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (3.14.1)
Collecting httpx-sse<1.0.0,>=0.4.0 (from langchain-community)
  Downloading httpx_sse-0.4.3-py3-none-any.whl.metadata (9.7 kB)
Collecting langchain-classic<2.0.0,>=1.0.7 (from langchain-community)
  Downloading langchain_classic-1.0.8-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: langsmith<1.0.0,>=0.1.125 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.10.2)
Requirement already satisfied: numpy>=1.26.2 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.0.2)
Collecting pydantic-settings<3.0.0,>=2.10.1 (from langchain-community)
  Downloading pydantic_settings-2.14.2-py3-none-any.whl.metadata (3.4 kB)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (6.0.3)
Collecting requests<3.0.0,>=2.32.5 (from langchain-community)
  Downloading requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: sqlalchemy<3.0.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.0.51)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (9.1.4)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.17 in /usr/local/lib/python3.12/dist-packages (from langchain-core) (0.0.18)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core) (26.2)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core) (4.16.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core) (0.17.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.24.2)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core) (3.1.1)
Collecting langchain-text-splitters<2.0.0,>=1.1.2 (from langchain-classic<2.0.0,>=1.0.7->langchain-community)
  Downloading langchain_text_splitters-1.1.2-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.3.0,>=1.2.5->langchain) (4.1.1)
Requirement already satisfied: langgraph-prebuilt<1.2.0,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.3.0,>=1.2.5->langchain) (1.1.0)
Requirement already satisfied: langgraph-sdk<0.5.0,>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.3.0,>=1.2.5->langchain) (0.4.2)
Requirement already satisfied: xxhash>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.3.0,>=1.2.5->langchain) (3.8.1)
Requirement already satisfied: anyio>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (4.14.2)
Requirement already satisfied: distro>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (3.11.9)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.0)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (1.3.1)
Requirement already satisfied: websockets>=15.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (15.0.1)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (1.2.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2.5.0)
Requirement already satisfied: certifi>=2023.5.7 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2026.6.17)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy<3.0.0,>=1.4.0->langchain-community) (3.5.3)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (0.16.0)
Requirement already satisfied: ormsgpack>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from langgraph-checkpoint<5.0.0,>=4.1.0->langgraph<1.3.0,>=1.2.5->langchain) (1.12.2)
Downloading langchain_community-0.4.2-py3-none-any.whl (2.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 43.2 MB/s eta 0:00:00
Downloading httpx_sse-0.4.3-py3-none-any.whl (9.0 kB)
Downloading langchain_classic-1.0.8-py3-none-any.whl (1.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 48.1 MB/s eta 0:00:00
Downloading pydantic_settings-2.14.2-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.7/61.7 kB 4.6 MB/s eta 0:00:00
Downloading requests-2.34.2-py3-none-any.whl (73 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 5.5 MB/s eta 0:00:00
Downloading langchain_text_splitters-1.1.2-py3-none-any.whl (35 kB)
Installing collected packages: requests, httpx-sse, pydantic-settings, langchain-text-splitters, langchain-classic, langchain-community
  Attempting uninstall: requests
    Found existing installation: requests 2.32.4
    Uninstalling requests-2.32.4:
      Successfully uninstalled requests-2.32.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.34.2 which is incompatible.
diffusers 0.39.0 requires huggingface-hub<2.0,>=0.34.0, but you have huggingface-hub 0.26.2 which is incompatible.
gradio 6.20.0 requires huggingface-hub<2.0,>=1.2.0, but you have huggingface-hub 0.26.2 which is incompatible.
Successfully installed httpx-sse-0.4.3 langchain-classic-1.0.8 langchain-community-0.4.2 langchain-text-splitters-1.1.2 pydantic-settings-2.14.2 requests-2.34.2

In [6]:
from langchain_core.tools import tool
@tool
def search_papers(query: str) -> str:
    """
    Search research papers from the FAISS database
    and return the most relevant results."""

In [7]:
!pip install -U langchain langchain-community langchain-huggingface

Requirement already satisfied: langchain in /usr/local/lib/python3.12/dist-packages (1.3.13)
Collecting langchain
  Downloading langchain-1.3.14-py3-none-any.whl.metadata (6.1 kB)
Requirement already satisfied: langchain-community in /usr/local/lib/python3.12/dist-packages (0.4.2)
Collecting langchain-huggingface
  Downloading langchain_huggingface-1.2.2-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: langchain-core<2.0.0,>=1.4.9 in /usr/local/lib/python3.12/dist-packages (from langchain) (1.4.9)
Requirement already satisfied: langgraph<1.3.0,>=1.2.5 in /usr/local/lib/python3.12/dist-packages (from langchain) (1.2.9)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain) (2.13.4)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (3.14.1)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.4.3)
Requirement already satisfied: langchain-classic<2.0.0,>=1.0.7 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (1.0.8)
Requirement already satisfied: langsmith<1.0.0,>=0.1.125 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.10.2)
Requirement already satisfied: numpy>=1.26.2 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.0.2)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.14.2)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (6.0.3)
Requirement already satisfied: requests<3.0.0,>=2.32.5 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.34.2)
Requirement already satisfied: sqlalchemy<3.0.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.0.51)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (9.1.4)
Collecting huggingface-hub<2.0.0,>=0.33.4 (from langchain-huggingface)
  Downloading huggingface_hub-1.24.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: tokenizers<1.0.0,>=0.19.1 in /usr/local/lib/python3.12/dist-packages (from langchain-huggingface) (0.20.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (0.5.2)
Requirement already satisfied: typing_extensions>=4.4 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (4.16.0)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.24.2)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (3.29.7)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (26.2)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (4.67.3)
Requirement already satisfied: langchain-text-splitters<2.0.0,>=1.1.2 in /usr/local/lib/python3.12/dist-packages (from langchain-classic<2.0.0,>=1.0.7->langchain-community) (1.1.2)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.9->langchain) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.17 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.9->langchain) (0.0.18)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.9->langchain) (0.17.0)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.3.0,>=1.2.5->langchain) (4.1.1)
Requirement already satisfied: langgraph-prebuilt<1.2.0,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.3.0,>=1.2.5->langchain) (1.1.0)
Requirement already satisfied: langgraph-sdk<0.5.0,>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.3.0,>=1.2.5->langchain) (0.4.2)
Requirement already satisfied: xxhash>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.3.0,>=1.2.5->langchain) (3.8.1)
Requirement already satisfied: anyio>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (4.14.2)
Requirement already satisfied: distro>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (1.9.0)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (3.11.9)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.0)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (1.3.1)
Requirement already satisfied: websockets>=15.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (15.0.1)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (1.2.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2.5.0)
Requirement already satisfied: certifi>=2023.5.7 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2026.6.17)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy<3.0.0,>=1.4.0->langchain-community) (3.5.3)
  Downloading huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.4.9->langchain) (3.1.1)
Requirement already satisfied: ormsgpack>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from langgraph-checkpoint<5.0.0,>=4.1.0->langgraph<1.3.0,>=1.2.5->langchain) (1.12.2)
Downloading langchain-1.3.14-py3-none-any.whl (139 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.6/139.6 kB 4.8 MB/s eta 0:00:00
Downloading langchain_huggingface-1.2.2-py3-none-any.whl (31 kB)
Downloading huggingface_hub-0.36.2-py3-none-any.whl (566 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 22.1 MB/s eta 0:00:00
Installing collected packages: huggingface-hub, langchain-huggingface, langchain
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface-hub 0.26.2
    Uninstalling huggingface-hub-0.26.2:
      Successfully uninstalled huggingface-hub-0.26.2
  Attempting uninstall: langchain
    Found existing installation: langchain 1.3.13
    Uninstalling langchain-1.3.13:
      Successfully uninstalled langchain-1.3.13
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gradio 6.20.0 requires huggingface-hub<2.0,>=1.2.0, but you have huggingface-hub 0.36.2 which is incompatible.
Successfully installed huggingface-hub-0.36.2 langchain-1.3.14 langchain-huggingface-1.2.2

In [8]:
from langchain_huggingface import HuggingFacePipeline

In [11]:
from transformers import pipeline
from langchain_huggingface import HuggingFacePipeline

# Initialize summarizer pipeline
summarizer = pipeline(
    "summarization",
    model="facebook/bart-large-cnn"
)

llm = HuggingFacePipeline(
    pipeline=summarizer
)

WARNING:torchao.kernel.intmm:Warning: Detected no triton, on systems without Triton certain kernels will not work
/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

In [12]:
llm

HuggingFacePipeline(metadata={'lc_versions': {'langchain-core': '1.4.9', 'langchain': '1.3.14'}}, pipeline=<transformers.pipelines.text2text_generation.SummarizationPipeline object at 0x79e7bf3cd8b0>, model_id='facebook/bart-large-cnn')

In [13]:
response = llm.invoke(
    "Deep Learning has become one of the most successful techniques for medical image reconstruction using convolutional neural networks."
)

Your max_length is set to 142, but your input_length is only 23. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=11)

In [14]:
response

"Deep Learning has become one of the most successful techniques for medical image reconstruction using convolutional neural networks. Deep Learning is a technique that uses deep neural networks to learn about a patient's medical history. It can also be used to learn more about a person's physical condition."

In [15]:
print(type(response))

<class 'str'>

In [26]:
!pip install -U langchain-groq

Requirement already satisfied: langchain-groq in /usr/local/lib/python3.12/dist-packages (1.1.3)
Requirement already satisfied: groq<1.0.0,>=0.30.0 in /usr/local/lib/python3.12/dist-packages (from langchain-groq) (0.37.1)
Requirement already satisfied: langchain-core<2.0.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-groq) (1.4.9)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (4.14.2)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (0.28.1)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (2.13.4)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.10 in /usr/local/lib/python3.12/dist-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (4.16.0)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.0->langchain-groq) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.17 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.0->langchain-groq) (0.0.18)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.0->langchain-groq) (0.10.2)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.0->langchain-groq) (26.2)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.0->langchain-groq) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.0->langchain-groq) (9.1.4)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.0->langchain-groq) (0.17.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->groq<1.0.0,>=0.30.0->langchain-groq) (3.18)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->groq<1.0.0,>=0.30.0->langchain-groq) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->groq<1.0.0,>=0.30.0->langchain-groq) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->groq<1.0.0,>=0.30.0->langchain-groq) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.4.0->langchain-groq) (3.1.1)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain-groq) (3.11.9)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain-groq) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain-groq) (2.34.2)
Requirement already satisfied: websockets>=15.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain-groq) (15.0.1)
Requirement already satisfied: xxhash>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain-groq) (3.8.1)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain-groq) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->groq<1.0.0,>=0.30.0->langchain-groq) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->groq<1.0.0,>=0.30.0->langchain-groq) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->groq<1.0.0,>=0.30.0->langchain-groq) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain-groq) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain-groq) (2.5.0)

In [24]:
from langchain_groq import ChatGroq

In [18]:
from google.colab import userdata

In [62]:
api_key = userdata.get("GROQ_API_KEY")

In [63]:
llm = ChatGroq(
    model="llama-3.1-8b-instant",
    api_key=api_key,
    temperature=0
)

In [32]:
response = llm.invoke("Hello, who are you?")

In [33]:
response

AIMessage(content="I'm an artificial intelligence model known as a large language model (LLM) or conversational AI. I'm a computer program designed to understand and respond to human language in a way that's natural and helpful.\n\nI don't have a personal identity or emotions like humans do, but I'm here to assist you with any questions, topics, or tasks you'd like to discuss. I can provide information, answer questions, generate text, and even engage in conversation.\n\nI'm constantly learning and improving my responses based on the conversations I have with users like you. So, feel free to ask me anything, and I'll do my best to help!", additional_kwargs={}, response_metadata={'token_usage': {'completion_tokens': 132, 'prompt_tokens': 41, 'total_tokens': 173, 'completion_time': 0.159709178, 'completion_tokens_details': None, 'prompt_time': 0.00250313, 'prompt_tokens_details': None, 'queue_time': 0.060809858, 'total_time': 0.162212308}, 'model_name': 'llama-3.1-8b-instant', 'system_fingerprint': 'fp_e2c608b1d6', 'service_tier': 'on_demand', 'finish_reason': 'stop', 'logprobs': None, 'model_provider': 'groq'}, id='lc_run--019f7430-f5fe-7062-af23-f8e5efc332ce-0', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 41, 'output_tokens': 132, 'total_tokens': 173})

In [34]:
response.content

"I'm an artificial intelligence model known as a large language model (LLM) or conversational AI. I'm a computer program designed to understand and respond to human language in a way that's natural and helpful.\n\nI don't have a personal identity or emotions like humans do, but I'm here to assist you with any questions, topics, or tasks you'd like to discuss. I can provide information, answer questions, generate text, and even engage in conversation.\n\nI'm constantly learning and improving my responses based on the conversations I have with users like you. So, feel free to ask me anything, and I'll do my best to help!"

In [35]:
from langchain_core.tools import tool

In [64]:
import faiss
from sentence_transformers import SentenceTransformer
from transformers import pipeline

@tool
def search_and_summarize(query: str, k: int = 5) -> str:
    """
    Search research papers from the FAISS database,
    retrieve the top-k most similar papers,
    summarize each paper using BART,
    and return the results.
    """
    global model, index, df, summarizer

    query_embedding = model.encode([query])

    faiss.normalize_L2(query_embedding)

    D, I = index.search(query_embedding, k)

    result = ""

    for rank, (score, idx) in enumerate(zip(D[0], I[0]), start=1):

        paper = df.iloc[idx]

        summary = summarizer(
            paper["abstract"],
            max_length=120,
            min_length=40,
            do_sample=False
        )[0]["summary_text"]

        result += f"Rank: {rank}\n"
        result += f"Similarity Score: {round(float(score),4)}\n"
        result += f"Title: {paper['title']}\n\n"

        result += paper["abstract"] + "\n\n"

        result += summary + "\n\n"

    return result

In [45]:
tools = [search_and_summarize]

In [46]:
from langchain.agents import create_agent

In [49]:
agent = create_agent(
    model=llm,
    tools=tools
)

In [70]:
response = agent.invoke(
    {
        "messages": [
            {
                "role": "user",
                "content": "Find the top 3 research papers on Vision Transformer."
            }
        ]
    }
)

In [71]:
response

{'messages': [HumanMessage(content='Find the top 3 research papers on Vision Transformer.', additional_kwargs={}, response_metadata={}, id='19d62d75-82c2-446a-aeeb-79ee8d825e67'),
  AIMessage(content='', additional_kwargs={'tool_calls': [{'id': 'd5j29trd4', 'function': {'arguments': '{"k":3,"query":"Vision Transformer"}', 'name': 'search_and_summarize'}, 'type': 'function'}]}, response_metadata={'token_usage': {'completion_tokens': 23, 'prompt_tokens': 376, 'total_tokens': 399, 'completion_time': 0.024215382, 'completion_tokens_details': None, 'prompt_time': 0.081825363, 'prompt_tokens_details': None, 'queue_time': 0.060842291, 'total_time': 0.106040745}, 'model_name': 'llama-3.1-8b-instant', 'system_fingerprint': 'fp_e2c608b1d6', 'service_tier': 'on_demand', 'finish_reason': 'tool_calls', 'logprobs': None, 'model_provider': 'groq'}, id='lc_run--019f7435-5881-7be2-a8c7-8da826c51aa1-0', tool_calls=[{'name': 'search_and_summarize', 'args': {'k': 3, 'query': 'Vision Transformer'}, 'id': 'd5j29trd4', 'type': 'tool_call'}], invalid_tool_calls=[], usage_metadata={'input_tokens': 376, 'output_tokens': 23, 'total_tokens': 399}),
  ToolMessage(content='[{"rank": 1, "similarity": 0.4415, "title": "Dense Transformer Networks", "abstract": "  The key idea of current deep learning methods for dense prediction is to\\napply a model on a regular patch centered on each pixel to make pixel-wise\\npredictions. These methods are limited in the sense that the patches are\\ndetermined by network architecture instead of learned from data. In this work,\\nwe propose the dense transformer networks, which can learn the shapes and sizes\\nof patches from data. The dense transformer networks employ an encoder-decoder\\narchitecture, and a pair of dense transformer modules are inserted into each of\\nthe encoder and decoder paths. The novelty of this work is that we provide\\ntechnical solutions for learning the shapes and sizes of patches from data and\\nefficiently restoring the spatial correspondence required for dense prediction.\\nThe proposed dense transformer modules are differentiable, thus the entire\\nnetwork can be trained. We apply the proposed networks on natural and\\nbiological image segmentation tasks and show superior performance is achieved\\nin comparison to baseline methods.\\n", "summary": "The key idea of current deep learning methods for dense prediction is toapply a model on a regular patch centered on each pixel to make pixel-wisepredictions. These methods are limited in the sense that the patches are determined by network architecture instead of learned from data. In this work, we propose the dense transformer networks, which can learn the shapes and sizes of patches fromData."}, {"rank": 2, "similarity": 0.4169, "title": "Inverse Compositional Spatial Transformer Networks", "abstract": "  In this paper, we establish a theoretical connection between the classical\\nLucas & Kanade (LK) algorithm and the emerging topic of Spatial Transformer\\nNetworks (STNs). STNs are of interest to the vision and learning communities\\ndue to their natural ability to combine alignment and classification within the\\nsame theoretical framework. Inspired by the Inverse Compositional (IC) variant\\nof the LK algorithm, we present Inverse Compositional Spatial Transformer\\nNetworks (IC-STNs). We demonstrate that IC-STNs can achieve better performance\\nthan conventional STNs with less model capacity; in particular, we show\\nsuperior performance in pure image alignment tasks as well as joint\\nalignment/classification problems on real-world problems.\\n", "summary": "In this paper, we establish a theoretical connection between the classicalLucas & Kanade (LK) algorithm and the emerging topic of Spatial TransformerNetworks (STNs) STNs are of interest to the vision and learning communitiesdue to their natural ability to combine alignment and classification within thesame theoretical framework."}, {"rank": 3, "similarity": 0.4107, "title": "gvnn: Neural Network Library for Geometric Computer Vision", "abstract": "  We introduce gvnn, a neural network library in Torch aimed towards bridging\\nthe gap between classic geometric computer vision and deep learning. Inspired\\nby the recent success of Spatial Transformer Networks, we propose several new\\nlayers which are often used as parametric transformations on the data in\\ngeometric computer vision. These layers can be inserted within a neural network\\nmuch in the spirit of the original spatial transformers and allow\\nbackpropagation to enable end-to-end learning of a network involving any domain\\nknowledge in geometric computer vision. This opens up applications in learning\\ninvariance to 3D geometric transformation for place recognition, end-to-end\\nvisual odometry, depth estimation and unsupervised learning through warping\\nwith a parametric transformation for image reconstruction error.\\n", "summary": "We introduce gvnn, a neural network library in Torch aimed towards bridging the gap between classic geometric computer vision and deep learning. Inspired by the recent success of Spatial Transformer Networks, we propose several new layers which are often used as parametric transformations on the data. These layers can be inserted within a neuralnetwork in the spirit of the original spatial transformers."}]', name='search_and_summarize', id='7c68b2bc-02c0-4093-9ed1-f7c11341b18c', tool_call_id='d5j29trd4'),
  AIMessage(content='The top 3 research papers on Vision Transformer are:\n\n1. "Dense Transformer Networks" - This paper proposes the dense transformer networks, which can learn the shapes and sizes of patches from data. The dense transformer networks employ an encoder-decoder architecture, and a pair of dense transformer modules are inserted into each of the encoder and decoder paths.\n2. "Inverse Compositional Spatial Transformer Networks" - This paper establishes a theoretical connection between the classical Lucas & Kanade (LK) algorithm and the emerging topic of Spatial Transformer Networks (STNs). STNs are of interest to the vision and learning communities due to their natural ability to combine alignment and classification within the same theoretical framework.\n3. "gvnn: Neural Network Library for Geometric Computer Vision" - This paper introduces gvnn, a neural network library in Torch aimed towards bridging the gap between classic geometric computer vision and deep learning. Inspired by the recent success of Spatial Transformer Networks, the authors propose several new layers which are often used as parametric transformations on the data in geometric computer vision.', additional_kwargs={}, response_metadata={'token_usage': {'completion_tokens': 213, 'prompt_tokens': 1241, 'total_tokens': 1454, 'completion_time': 0.197171211, 'completion_tokens_details': None, 'prompt_time': 0.069282704, 'prompt_tokens_details': None, 'queue_time': 0.061124944, 'total_time': 0.266453915}, 'model_name': 'llama-3.1-8b-instant', 'system_fingerprint': 'fp_e2c608b1d6', 'service_tier': 'on_demand', 'finish_reason': 'stop', 'logprobs': None, 'model_provider': 'groq'}, id='lc_run--019f7436-1d8b-7e43-90fa-8bc361db49b3-0', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 1241, 'output_tokens': 213, 'total_tokens': 1454})]}

In [72]:
print(type(response))

<class 'dict'>

In [73]:
print(response.keys())

dict_keys(['messages'])

In [74]:
len(response["messages"])

4

In [75]:
response["messages"][0]

HumanMessage(content='Find the top 3 research papers on Vision Transformer.', additional_kwargs={}, response_metadata={}, id='19d62d75-82c2-446a-aeeb-79ee8d825e67')

In [76]:
response["messages"][1]

AIMessage(content='', additional_kwargs={'tool_calls': [{'id': 'd5j29trd4', 'function': {'arguments': '{"k":3,"query":"Vision Transformer"}', 'name': 'search_and_summarize'}, 'type': 'function'}]}, response_metadata={'token_usage': {'completion_tokens': 23, 'prompt_tokens': 376, 'total_tokens': 399, 'completion_time': 0.024215382, 'completion_tokens_details': None, 'prompt_time': 0.081825363, 'prompt_tokens_details': None, 'queue_time': 0.060842291, 'total_time': 0.106040745}, 'model_name': 'llama-3.1-8b-instant', 'system_fingerprint': 'fp_e2c608b1d6', 'service_tier': 'on_demand', 'finish_reason': 'tool_calls', 'logprobs': None, 'model_provider': 'groq'}, id='lc_run--019f7435-5881-7be2-a8c7-8da826c51aa1-0', tool_calls=[{'name': 'search_and_summarize', 'args': {'k': 3, 'query': 'Vision Transformer'}, 'id': 'd5j29trd4', 'type': 'tool_call'}], invalid_tool_calls=[], usage_metadata={'input_tokens': 376, 'output_tokens': 23, 'total_tokens': 399})

In [77]:
response["messages"][2]

ToolMessage(content='[{"rank": 1, "similarity": 0.4415, "title": "Dense Transformer Networks", "abstract": "  The key idea of current deep learning methods for dense prediction is to\\napply a model on a regular patch centered on each pixel to make pixel-wise\\npredictions. These methods are limited in the sense that the patches are\\ndetermined by network architecture instead of learned from data. In this work,\\nwe propose the dense transformer networks, which can learn the shapes and sizes\\nof patches from data. The dense transformer networks employ an encoder-decoder\\narchitecture, and a pair of dense transformer modules are inserted into each of\\nthe encoder and decoder paths. The novelty of this work is that we provide\\ntechnical solutions for learning the shapes and sizes of patches from data and\\nefficiently restoring the spatial correspondence required for dense prediction.\\nThe proposed dense transformer modules are differentiable, thus the entire\\nnetwork can be trained. We apply the proposed networks on natural and\\nbiological image segmentation tasks and show superior performance is achieved\\nin comparison to baseline methods.\\n", "summary": "The key idea of current deep learning methods for dense prediction is toapply a model on a regular patch centered on each pixel to make pixel-wisepredictions. These methods are limited in the sense that the patches are determined by network architecture instead of learned from data. In this work, we propose the dense transformer networks, which can learn the shapes and sizes of patches fromData."}, {"rank": 2, "similarity": 0.4169, "title": "Inverse Compositional Spatial Transformer Networks", "abstract": "  In this paper, we establish a theoretical connection between the classical\\nLucas & Kanade (LK) algorithm and the emerging topic of Spatial Transformer\\nNetworks (STNs). STNs are of interest to the vision and learning communities\\ndue to their natural ability to combine alignment and classification within the\\nsame theoretical framework. Inspired by the Inverse Compositional (IC) variant\\nof the LK algorithm, we present Inverse Compositional Spatial Transformer\\nNetworks (IC-STNs). We demonstrate that IC-STNs can achieve better performance\\nthan conventional STNs with less model capacity; in particular, we show\\nsuperior performance in pure image alignment tasks as well as joint\\nalignment/classification problems on real-world problems.\\n", "summary": "In this paper, we establish a theoretical connection between the classicalLucas & Kanade (LK) algorithm and the emerging topic of Spatial TransformerNetworks (STNs) STNs are of interest to the vision and learning communitiesdue to their natural ability to combine alignment and classification within thesame theoretical framework."}, {"rank": 3, "similarity": 0.4107, "title": "gvnn: Neural Network Library for Geometric Computer Vision", "abstract": "  We introduce gvnn, a neural network library in Torch aimed towards bridging\\nthe gap between classic geometric computer vision and deep learning. Inspired\\nby the recent success of Spatial Transformer Networks, we propose several new\\nlayers which are often used as parametric transformations on the data in\\ngeometric computer vision. These layers can be inserted within a neural network\\nmuch in the spirit of the original spatial transformers and allow\\nbackpropagation to enable end-to-end learning of a network involving any domain\\nknowledge in geometric computer vision. This opens up applications in learning\\ninvariance to 3D geometric transformation for place recognition, end-to-end\\nvisual odometry, depth estimation and unsupervised learning through warping\\nwith a parametric transformation for image reconstruction error.\\n", "summary": "We introduce gvnn, a neural network library in Torch aimed towards bridging the gap between classic geometric computer vision and deep learning. Inspired by the recent success of Spatial Transformer Networks, we propose several new layers which are often used as parametric transformations on the data. These layers can be inserted within a neuralnetwork in the spirit of the original spatial transformers."}]', name='search_and_summarize', id='7c68b2bc-02c0-4093-9ed1-f7c11341b18c', tool_call_id='d5j29trd4')

In [78]:
response["messages"][3]

AIMessage(content='The top 3 research papers on Vision Transformer are:\n\n1. "Dense Transformer Networks" - This paper proposes the dense transformer networks, which can learn the shapes and sizes of patches from data. The dense transformer networks employ an encoder-decoder architecture, and a pair of dense transformer modules are inserted into each of the encoder and decoder paths.\n2. "Inverse Compositional Spatial Transformer Networks" - This paper establishes a theoretical connection between the classical Lucas & Kanade (LK) algorithm and the emerging topic of Spatial Transformer Networks (STNs). STNs are of interest to the vision and learning communities due to their natural ability to combine alignment and classification within the same theoretical framework.\n3. "gvnn: Neural Network Library for Geometric Computer Vision" - This paper introduces gvnn, a neural network library in Torch aimed towards bridging the gap between classic geometric computer vision and deep learning. Inspired by the recent success of Spatial Transformer Networks, the authors propose several new layers which are often used as parametric transformations on the data in geometric computer vision.', additional_kwargs={}, response_metadata={'token_usage': {'completion_tokens': 213, 'prompt_tokens': 1241, 'total_tokens': 1454, 'completion_time': 0.197171211, 'completion_tokens_details': None, 'prompt_time': 0.069282704, 'prompt_tokens_details': None, 'queue_time': 0.061124944, 'total_time': 0.266453915}, 'model_name': 'llama-3.1-8b-instant', 'system_fingerprint': 'fp_e2c608b1d6', 'service_tier': 'on_demand', 'finish_reason': 'stop', 'logprobs': None, 'model_provider': 'groq'}, id='lc_run--019f7436-1d8b-7e43-90fa-8bc361db49b3-0', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 1241, 'output_tokens': 213, 'total_tokens': 1454})

In [79]:
import faiss
from sentence_transformers import SentenceTransformer
from transformers import pipeline

@tool
def search_and_summarize(query: str, k: int = 5):
    """
    Search research papers from the FAISS database,
    retrieve the top-k most similar papers,
    summarize each paper using BART,
    and return the results as structured data.
    """
    global model, index, df, summarizer

    query_embedding = model.encode([query])

    faiss.normalize_L2(query_embedding)

    D, I = index.search(query_embedding, k)

    papers = []

    for rank, (score, idx) in enumerate(zip(D[0], I[0]), start=1):

        paper = df.iloc[idx]

        summary = summarizer(
            paper["abstract"],
            max_length=120,
            min_length=40,
            do_sample=False
        )[0]["summary_text"]

        paper_data = {
            "rank": rank,
            "similarity": round(float(score), 4),
            "title": paper["title"],
            "abstract": paper["abstract"],
            "summary": summary
        }

        papers.append(paper_data)

    return papers

In [80]:
from keybert import KeyBERT

@tool
def extract_keywords(text: str, top_n: int = 5) -> str:
    """
    Extract the most important keywords from the given text
    using the KeyBERT model.
    """
    global kw_model

    keywords = kw_model.extract_keywords(
        text,
        keyphrase_ngram_range=(1, 2),
        stop_words="english",
        top_n=top_n
    )

    result = "Top Keywords:\n\n"

    for rank, (keyword, score) in enumerate(keywords, start=1):

        result += (
            f"{rank}. {keyword} "
            f"(Relevance Score: {round(score, 4)})\n"
        )

    return result

In [81]:
tools = [
    search_and_summarize,
    extract_keywords
]

In [82]:
agent = create_agent(
    model=llm,
    tools=tools
)

In [83]:
print(tools)

[StructuredTool(name='search_and_summarize', description='Search research papers from the FAISS database,\nretrieve the top-k most similar papers,\nsummarize each paper using BART,\nand return the results as structured data.', args_schema=<class 'langchain_core.utils.pydantic.search_and_summarize'>, func=<function search_and_summarize at 0x79e75f0a68e0>), StructuredTool(name='extract_keywords', description='Extract the most important keywords from the given text\nusing the KeyBERT model.', args_schema=<class 'langchain_core.utils.pydantic.extract_keywords'>, func=<function extract_keywords at 0x79e75f0a6660>)]

In [85]:
response = extract_keywords.invoke(
    {
        "text": "Deep Learning for Medical Image Reconstruction",
        "top_n": 5
    }
)

print(response)

Top Keywords:

1. image reconstruction (Relevance Score: 0.5655)
2. deep learning (Relevance Score: 0.526)
3. medical image (Relevance Score: 0.4839)
4. learning medical (Relevance Score: 0.4024)
5. reconstruction (Relevance Score: 0.3745)

In [86]:
user_query = "Extract the top 5 keywords from Deep Learning for Medical Image Reconstruction."

llm_with_tools = llm.bind_tools(tools)

response = llm_with_tools.invoke(user_query)

print(response)



print(response.tool_calls)




tool_call = response.tool_calls[0]

print(tool_call)

content='' additional_kwargs={'tool_calls': [{'id': '0x4btxmnm', 'function': {'arguments': '{"text":"Deep Learning for Medical Image Reconstruction","top_n":5}', 'name': 'extract_keywords'}, 'type': 'function'}]} response_metadata={'token_usage': {'completion_tokens': 26, 'prompt_tokens': 379, 'total_tokens': 405, 'completion_time': 0.029917156, 'completion_tokens_details': None, 'prompt_time': 0.022627575, 'prompt_tokens_details': None, 'queue_time': 0.061108434, 'total_time': 0.052544731}, 'model_name': 'llama-3.1-8b-instant', 'system_fingerprint': 'fp_e2c608b1d6', 'service_tier': 'on_demand', 'finish_reason': 'tool_calls', 'logprobs': None, 'model_provider': 'groq'} id='lc_run--019f7439-1b92-7a71-8f01-c5ea03152659-0' tool_calls=[{'name': 'extract_keywords', 'args': {'text': 'Deep Learning for Medical Image Reconstruction', 'top_n': 5}, 'id': '0x4btxmnm', 'type': 'tool_call'}] invalid_tool_calls=[] usage_metadata={'input_tokens': 379, 'output_tokens': 26, 'total_tokens': 405}
[{'name': 'extract_keywords', 'args': {'text': 'Deep Learning for Medical Image Reconstruction', 'top_n': 5}, 'id': '0x4btxmnm', 'type': 'tool_call'}]
{'name': 'extract_keywords', 'args': {'text': 'Deep Learning for Medical Image Reconstruction', 'top_n': 5}, 'id': '0x4btxmnm', 'type': 'tool_call'}

In [87]:
tool_name = tool_call["name"]

print(tool_name)

extract_keywords

In [88]:
tool_args = tool_call["args"]

print(tool_args)

{'text': 'Deep Learning for Medical Image Reconstruction', 'top_n': 5}

In [89]:
if tool_name == "extract_keywords":

    tool_result = extract_keywords.invoke(tool_args)

elif tool_name == "search_and_summarize":

    tool_result = search_and_summarize.invoke(tool_args)

print(tool_result)

Top Keywords:

1. image reconstruction (Relevance Score: 0.5655)
2. deep learning (Relevance Score: 0.526)
3. medical image (Relevance Score: 0.4839)
4. learning medical (Relevance Score: 0.4024)
5. reconstruction (Relevance Score: 0.3745)

In [90]:
from langchain_core.messages import ToolMessage

In [91]:
tool_message = ToolMessage(
    content=tool_result,
    tool_call_id=tool_call["id"]
)

In [92]:
print(tool_message)

content='Top Keywords:\n\n1. image reconstruction (Relevance Score: 0.5655)\n2. deep learning (Relevance Score: 0.526)\n3. medical image (Relevance Score: 0.4839)\n4. learning medical (Relevance Score: 0.4024)\n5. reconstruction (Relevance Score: 0.3745)\n' tool_call_id='0x4btxmnm'

In [93]:
from langchain_core.messages import SystemMessage, HumanMessage

final_response = llm.invoke(
    [
        SystemMessage(
            content="""
You are a helpful AI assistant.

Rules:
1. Always use the tool output.
2. Never ignore tool results.
3. Present the complete tool output.
4. Add a short explanation after the tool output if necessary.
"""
        ),

        HumanMessage(content=user_query),

        response,

        tool_message
    ]
)

print(final_response.content)

The top 5 keywords extracted from the given text are related to the field of medical image reconstruction using deep learning techniques. These keywords can be useful for search engine optimization (SEO), topic modeling, or information retrieval tasks.

In [94]:
from langchain_core.messages import (
    SystemMessage,
    HumanMessage
)

final_response = llm.invoke(
[
SystemMessage(
content="""
You are a research assistant.

IMPORTANT RULES

1. Never ignore tool output.

2. Always display every keyword returned by the tool.

3. Do not summarize the keywords.

4. Print the keywords exactly as received.

5. After printing them, give a short explanation.
"""
),

HumanMessage(content=user_query),

response,

tool_message

]
)

print(final_response.content)

Explanation: The top 5 keywords extracted from the given topic are related to the application of deep learning techniques in medical image reconstruction. These keywords highlight the importance of using deep learning algorithms to improve the quality and accuracy of medical images, which is a crucial aspect of medical imaging.

In [67]:
from langchain_core.tools import tool

@tool
def compare_papers(
    paper1: str,
    paper2: str
) -> str:
    """
    Compare two research papers based on their abstracts.
    The tool retrieves the closest matching papers from the FAISS database
    and uses the LLM to compare them.
    """
    global model, index, df, llm

    embedding1 = model.encode([paper1])

    faiss.normalize_L2(embedding1)

    D1, I1 = index.search(embedding1, 1)

    first_paper = df.iloc[I1[0][0]]

    embedding2 = model.encode([paper2])

    faiss.normalize_L2(embedding2)

    D2, I2 = index.search(embedding2, 1)

    second_paper = df.iloc[I2[0][0]]

    comparison_prompt = f"""
Compare the following two research papers.

Paper 1

Title:
{first_paper['title']}

Abstract:
{first_paper['abstract']}


Paper 2

Title:
{second_paper['title']}

Abstract:
{second_paper['abstract']}


Compare them based on:

1. Research Objective

2. Methodology

3. Key Contributions

4. Advantages

5. Limitations

6. Applications

Present the comparison in a clear table.
"""

    response = llm.invoke(comparison_prompt)

    return response.content

In [95]:
from langgraph.prebuilt import create_react_agent
from langchain_core.messages import HumanMessage

# 1. Group all your created tools into a single list
tools = [
    search_and_summarize,
    extract_keywords,
    compare_papers
]

# 2. Create the ReAct agent using LangGraph
# This binds your Groq LLM with the provided tools
agent_executor = create_react_agent(llm, tools)

print("Agent successfully initialized with tools:", [t.name for t in tools])

Agent successfully initialized with tools: ['search_and_summarize', 'extract_keywords', 'compare_papers']

/tmp/ipykernel_23130/3766881740.py:13: LangGraphDeprecatedSinceV10: create_react_agent has been moved to `langchain.agents`. Please update your import to `from langchain.agents import create_agent`. Deprecated in LangGraph V1.0 to be removed in V2.0.
  agent_executor = create_react_agent(llm, tools)